### ISSUE TITLE
Cannot find module 'react-native'

### ISSUE THREAD

**Issue by mattrei** [threepointone/react-ease#1]
Hi,

great library you have here! 
However I can't use it in the browser right now :(. It gives me the message: 
`Error: Cannot find module 'react-native' from '/home/mat/dev/aleatory/tails/node_modules/react-ease'`

Oh and when do you think you will commit the infinite repeating option for the animations?

Thanks,
Matthias

**Comment by threepointone** [comment]
just pushed an npm build that removed the react-native hack, should work when you update. I'll fix the infinite repeat option soon, made a fresh issue for that here - #2

**Comment by threepointone** [comment]
`repeat={Infinity}` should now work.

**Comment by mattrei** [comment]
Hi, thanks for fixing. 
However with version 1.0.6 I get now the following error

```
/home/mat/dev/aleatory/tails/node_modules/react-ease/components.js:1
import {Easing, defaults} from './ease';
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'
```

**Comment by threepointone** [comment]
damn, I boobooed this during the refactor. please give me a couple of hours, will fix.

**Comment by threepointone** [comment]
pushed a possible fix. update and try now?

**Comment by threepointone** [comment]
closing.
