### ISSUE TITLE
Uncaught TypeError: this.props.children is not a function

### ISSUE THREAD

**Issue by skeie** [threepointone/react-ease#4]
Hi,

I am trying this example:      

```
 <Ease from={0} to={100} duration={500}>
          {val => <div>{val}</div>}     // yes, children is a function
  </Ease>
```

When I do, I get this error from the browser console:

Uncaught TypeError: this.props.children is not a function - components.js:56

Any suggestions?

**Comment by threepointone** [comment]
this usually happens when there's trailing space around the child-function's brackets. Try this - 

```
<Ease from={0} to={100} duration={500}>{
    val => <div>{val}</div>
}</Ease>
```

**Comment by skeie** [comment]
Thanks man! :+1:
